# Generated by Django 3.2 on 2021-04-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_username', models.CharField(max_length=50)),
                ('facebook_passsword', models.CharField(max_length=50)),
            ],
        ),
    ]
