# Generated by Django 3.2 on 2021-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
