# Generated by Django 3.2 on 2021-04-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General_App', '0002_category_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyName',
            new_name='CompanyType',
        ),
        migrations.RenameField(
            model_name='companytype',
            old_name='name',
            new_name='type_name',
        ),
    ]
