# Generated by Django 3.2 on 2021-04-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General_App', '0003_auto_20210422_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessaccount',
            old_name='comapny_planS',
            new_name='comapny_plan',
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General_App.role')),
            ],
        ),
    ]
